/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modulo;

/**
 *
 * @author Usuario-108
 */
public class frmnInicio extends javax.swing.JFrame {

    /**
     * Creates new form frmnInicio
     */
    public frmnInicio() {
        initComponents();
        //para centrar la wea de formulario
        
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        MnuGestion = new javax.swing.JMenuBar();
        mnuGestionar = new javax.swing.JMenu();
        MnuItemAlumno = new javax.swing.JMenuItem();
        MenuItemDocente = new javax.swing.JMenuItem();
        MenuItemRamo = new javax.swing.JMenuItem();
        mnuIngresar = new javax.swing.JMenu();
        jMenuItemNotas = new javax.swing.JMenuItem();
        jMenuItemConsultar = new javax.swing.JMenuItem();
        mnuCertificados = new javax.swing.JMenu();
        jMenuItemImprimirCertificados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        mnuGestionar.setText("Gestionar");

        MnuItemAlumno.setText("Alumno");
        MnuItemAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnuItemAlumnoActionPerformed(evt);
            }
        });
        mnuGestionar.add(MnuItemAlumno);

        MenuItemDocente.setText("Docente");
        mnuGestionar.add(MenuItemDocente);

        MenuItemRamo.setText("Ramo");
        mnuGestionar.add(MenuItemRamo);

        MnuGestion.add(mnuGestionar);

        mnuIngresar.setText("Ingresar");

        jMenuItemNotas.setText("Ingresar Notas");
        jMenuItemNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNotasActionPerformed(evt);
            }
        });
        mnuIngresar.add(jMenuItemNotas);

        jMenuItemConsultar.setText("Consultar Notas");
        mnuIngresar.add(jMenuItemConsultar);

        MnuGestion.add(mnuIngresar);

        mnuCertificados.setText("Certificados de Notas");

        jMenuItemImprimirCertificados.setText("Imprimir Certificados de Notas");
        mnuCertificados.add(jMenuItemImprimirCertificados);

        MnuGestion.add(mnuCertificados);

        setJMenuBar(MnuGestion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemNotasActionPerformed

    private void MnuItemAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuItemAlumnoActionPerformed
        // TODO add your handling code here:
         frmnAlumno nuevoFrmn = new frmnAlumno();
                // jDesktopPane1.add(nuevoFrmn);
                nuevoFrmn.setVisible(true);
                this.dispose();
                
    }//GEN-LAST:event_MnuItemAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmnInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmnInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmnInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmnInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmnInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItemDocente;
    private javax.swing.JMenuItem MenuItemRamo;
    private javax.swing.JMenuBar MnuGestion;
    private javax.swing.JMenuItem MnuItemAlumno;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jMenuItemConsultar;
    private javax.swing.JMenuItem jMenuItemImprimirCertificados;
    private javax.swing.JMenuItem jMenuItemNotas;
    private javax.swing.JMenu mnuCertificados;
    private javax.swing.JMenu mnuGestionar;
    private javax.swing.JMenu mnuIngresar;
    // End of variables declaration//GEN-END:variables
}
